# This workflow installs Apama Community Edition and uses it to run PySys tests for your application

# Python 3 and Java JDK 8 are shipped with Apama (and added to PATH by this workflow) so there is no need to install them separately. 

# Using this workflow implies that you have agreed to the terms of the Software AG license agreement - see http://www.apamacommunity.com/terms-conditions/
# This workflow can be used without a commercial license of Apama. If you do have a commercial Apama license you hereby 
# agree not to commit the license file to any repository or location that can be accessed outside your organization. 

name: PySys

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    env:
      # Keep this updated with the latest version from http://www.apamacommunity.com/downloads/
      WORKFLOW_APAMA_VERSION: 10.5.3.2

    strategy:
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      
      matrix:
        include:
          - run-id: amd64_linux
            os: ubuntu-latest
            upload-docs: true
            
          - run-id: amd64_win
            os: windows-latest
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Install the full Apama Community Edition. This contains useful tools such as apamadoc/apama_project 
      # which are not in the smaller "core" package

      - uses: actions/checkout@v2

      - name: Apama installation cache
        # always-upload is a fork of actions/cache allows cache to be saved even if some later steps (e.g. testing) fail
        uses: pat-s/always-upload-cache@v2.1.3

        id: cache-apama-installer
        with:
            path: ~/cached-apama-installation.tar
            # To use a clean cache, add extra chars to this key
            key: apama-${{ matrix.run-id }}-${{ env.WORKFLOW_APAMA_VERSION }}-TODOx24

      - name: Download Apama
        uses: carlosperate/download-file-action@v1.0.3
        id: download-apama
        if: steps.cache-apama-installer.outputs.cache-hit != 'true'
        with:
           file-url: 'https://downloads.apamacommunity.com/apama/${{ env.WORKFLOW_APAMA_VERSION }}/apama_${{ env.WORKFLOW_APAMA_VERSION }}_${{ matrix.run-id }}.zip'
           file-name: apama-installer.zip
           location: ../apama-installer

      - name: Install Apama
        shell: bash
        run: |
          APAMA_CACHE_TAR=~/cached-apama-installation.tar
          echo Cache location: $APAMA_CACHE_TAR

          if [[ ${{runner.os}} = Windows ]]; then
            _SAG_INSTALL_PATH=c:\\SoftwareAG
          else
            _SAG_INSTALL_PATH=/opt/softwareag
          fi
          
          if [[ "${{ steps.cache-apama-installer.outputs.cache-hit }}" = "true" ]]; then
            echo Unpacking Apama installation from cache
            
            mkdir $_SAG_INSTALL_PATH
            cd $_SAG_INSTALL_PATH
            tar -xf $APAMA_CACHE_TAR

            # Check it unpacked correctly
            ls $_SAG_INSTALL_PATH/Apama > /dev/null
          else
            # Cache miss - need to install it
            cd ../apama-installer
            unzip -q apama-installer.zip
            mv apama_*/* ./
            
            cat > apama-installer-script.txt << EOF
          LicenseAgree=Accept
          InstallProducts=e2ei/11/.latest/Apama/PAMServer
          PAM.Work.Directory.ID=__VERSION1__,$_SAG_INSTALL_PATH/apama-work
          InstallDir=$_SAG_INSTALL_PATH
          sagInstallerLogFile=softwareag-installer.log
          imageFile=data/SAGImage.zip
          EOF
            # Need to escape backslashes as it's effectively a properties file
            sed -i 's/\\/\\\\/g' apama-installer-script.txt
            
            echo Running installer with script:
            cat apama-installer-script.txt
            
            ./install -readScript apama-installer-script.txt -console -scriptErrorInteract no
            
            # Double-check that it was installed
            ls $_SAG_INSTALL_PATH/Apama/bin > /dev/null
            
            # Archive a pristine copy of the installation for the cache (before running any tests); 
            # no need to compress as the cache already does that
            cd $_SAG_INSTALL_PATH
            tar -cf $APAMA_CACHE_TAR *
          fi

          cd ~

          # Until Apama 10.7 we need to explicitly enable it (and disable colorama on windows which would replace the escape codes)
          echo PYSYS_COLOR=true >> $GITHUB_ENV
          echo PYSYS_DISABLE_COLORAMA=true >> $GITHUB_ENV
          
          # Once installed, copy the entire apama environment into the GH Actions env so it can be used in any type of 
          # shell (bash/cmd/PS etc). We also set an extra env var APAMA_PYSYS so user can run pysys from any shell. 
          if [[ ${{runner.os}} = Windows ]]; then
            echo "APAMA_PYSYS=pysys.cmd" >> $GITHUB_ENV

            echo "APAMA_HOME=`cygpath --windows $_SAG_INSTALL_PATH/Apama`" >> $GITHUB_ENV
            # For Windows we need to do it all in a separate (cmd) step otherwise extra vars from Git Bash will leak in
          else
            echo "APAMA_PYSYS=pysys" >> $GITHUB_ENV

            . $_SAG_INSTALL_PATH/Apama/bin/apama_env
            env | sort >> apama.env

            # This will replace the environment to point at Apama rather than GH Actions pre-installed tools, which ensures
            # the right version of Ant/Java etc is used
            cat apama.env >> $GITHUB_ENV
          fi

      - name: Setup Apama environment on Windows
        if: matrix.run-id == 'amd64_win'
        shell: cmd
        run: |
          call %APAMA_HOME%\bin\apama_env.bat
          set > apama.env
          type apama.env >> %GITHUB_ENV%

      # TODO: remove these actions unless compiling custom C++/Java plugins is required 
      # (especially on Windows, as it's quite time-consuming to install the SDK)
      - name: Install Windows 8.1 SDK (C++)
        if: matrix.run-id == 'amd64_win DISABLED'
        shell: powershell
        run: |
          Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
          Get-Date
          Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
      - name: Setup Visual Studio
        if: matrix.run-id == 'amd64_win DISABLED'
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[14,17]'
      - name: Build C++ plugins (Windows)
        shell: cmd
        if: matrix.run-id == 'amd64_win DISABLED'
        run: |
          pushd %APAMA_HOME%\samples\correlator_plugin\cpp
          msbuild /p:platform=x64 correlator_plugin_cpp_api.sln

          mkdir %GITHUB_WORKSPACE%\src\lib
          echo Copying into Apama project dir:
          copy Release\*.dll %GITHUB_WORKSPACE%\src\lib
          copy Release\*.pdb %GITHUB_WORKSPACE%\src\lib
      - name: Build C++ plugins (Linux)
        shell: bash
        if: matrix.run-id != 'amd64_win'
        run: |
          cd $APAMA_HOME/samples/correlator_plugin/cpp
          make

          ls *.so
          mkdir --parents $GITHUB_WORKSPACE/src/lib
          cp lib*.so $GITHUB_WORKSPACE/src/lib/

      - name: Build Java plugins
        shell: bash
        run: |
          env
          cd $APAMA_HOME/samples/correlator_plugin/java
          ant
          mkdir --parents $GITHUB_WORKSPACE/src/lib
          cp *.jar $GITHUB_WORKSPACE/src/lib/

      - name: Deploy Apama project
        shell: bash
        run: |
          engine_deploy --outputDeployDir __deploydir src
          ls __deploydir

      - name: PySys tests
        working-directory: test
        shell: bash
        id: pysys
        run: |
          ls ..
          $APAMA_PYSYS run --threads=auto --record --purge --printLogs=ALL -Xeplcoverage -XcodeCoverage --mode=ALL --outdir=`pwd`/__pysys_output/${{matrix.run-id}} 

      # If any tests fail, PySys will return an error code, so we need "if: always()" so the following steps will run
      # Since we expect failures only from the cookbook sample, that's the one we upload artifacts for (using id=pysys)
      # The follow lines are a copy from the sample pysys workflow

      - name: Upload archive artifacts for any test failures
        uses: actions/upload-artifact@v2
        if: failure()

        with:
          name: pysys_output_${{matrix.run-id}}
          path: test/__pysys_output/${{matrix.run-id}}

      - name: Upload EPL code coverage report
        uses: actions/upload-artifact@v2
        if: success()

        with:
          name: pysys_epl_coverage_${{matrix.run-id}}
          path: test/__pysys_output/${{matrix.run-id}}/eplcoverage

      - name: Build ApamaDoc
        shell: bash
        if: always()
        run: |
          mkdir --parents __build/apamadoc
          apamadoc __build/apamadoc $APAMA_HOME/samples/epl/simple
     
      - name: Upload ApamaDoc to gh-pages
        if: matrix.upload-docs
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: __build/apamadoc
